<HTML>
<HEAD>
##HEAD##
</HEAD>
<BODY BGCOLOR=white TEXT=black>
<TABLE BORDER=1 BGCOLOR="#cccccc" WIDTH=800 ALIGN="left" VALIGN="top">
  ##FUNCTIONZONE##
  ##MENU##
  ##MAINPANE##
</TABLE>
</TABLE>
</BODY>
</HTML>
